import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
export default function Layout() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Chat Realtime App</title>
        <meta name="description" content="Generated by create chat realtime app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav>
      <ul>
      <li>
        <Link href="/">Home</Link>
      </li>
      <li>
        <Link href="/login">
          Login
        </Link>
      </li>
      <li>
        <Link href="/blog/hello-world">Blog Post</Link>
      </li>
    </ul>
      </nav>
    </div>
  )
}
