import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useRouter } from "next/router";
import { useEffect,HTMLAttributes,ReactNode } from "react";
type Layout = {
  children: ReactNode,
  href: string
  prefetch?: boolean
} & HTMLAttributes<HTMLAnchorElement>
export default function Layout({children,href,prefetch=false}:Layout) {
  const router = useRouter();
  useEffect(() => {
      router.prefetch(href);
      handleRouter()
  }, [])
  const handleRouter =async () => {
    try {
      if(prefetch){
         router.push(href);
      }
    } catch (err) {
      console.log(err)
    }
  }
  return (
    <>
    <div className={styles.container}>
      <Head>
        <title>Chat Realtime App</title>
        <meta
          name="description"
          content="Generated by create chat realtime app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
      {children}
    </>
  );
}
